# Generated by Django 4.2.7 on 2023-11-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0003_alter_card_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('other_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.card')),
                ('selected_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.card')),
            ],
        ),
    ]
