# Generated by Django 4.2.7 on 2023-12-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('choices', '0002_alter_choice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='selected_card',
        ),
        migrations.AddField(
            model_name='choice',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
            preserve_default=False,
        ),
    ]
