# Generated by Django 4.2.7 on 2023-12-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_deck'),
        ('choices', '0003_remove_choice_selected_card_choice_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cards.card'),
        ),
    ]
