# Generated by Django 4.2.7 on 2023-11-20 13:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='flags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AL', 'Alcohol Related')], max_length=2),
        ),
    ]
