# Generated by Django 4.2.7 on 2023-11-28 18:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AL', 'Alcohol Related')], max_length=3),
        ),
    ]
