# Generated by Django 4.2.7 on 2023-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='flags',
        ),
        migrations.AddField(
            model_name='card',
            name='noAlcohol',
            field=models.BooleanField(default=False),
        ),
    ]
