# Generated by Django 4.2.7 on 2023-12-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_flags_card_noalcohol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='noAlcohol',
            new_name='no_alcohol',
        ),
    ]
